package cn.itcast.ssm.mapper;

import cn.itcast.ssm.po.User;
import cn.itcast.ssm.po.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    @Insert("INSERT INTO game_server (ID,GROUP_NAME,GAME_IP,TITLE,OPERATOR_ID,OPEN_TIME,SERVER_URL,SERVER_DB_NAME,LOG_DB_NAME,WEB_SITE,BBS_URL,KE_URL,DC_KEY,SERVER_KEY,RECHARGE_URL,FCM_TIME,CHAT_URL,CHAT_PORT,IS_WEIDUAN,LOG_IP,IS_DELETE,IS_UNITED,CREATE_TIME) VALUES (#{id},#{groupName},#{gameIp},#{title},#{operatorId},#{openTime},#{serverUrl},#{serverDbName},#{logDbName},#{webSite},#{bbsUrl},#{keUrl},#{dcKey},#{serverKey},#{rechargeUrl},#{fcmTime},#{chatUrl},#{chatPort},#{isWeiduan},#{logIp},#{isDelete},#{isUnited},#{createTime})")
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 09 18:12:58 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);
}